#!/usr/bin/env python3
"""first list of databases in MongoDB"""

from pymongo import MongoClient

client = MongoClient('mongodb://172.17.0.2:27017')

databases = client.list_database_names()
print("database names: ", databases)
